// Verify that the vendored Semaphore artifacts on disk match the SHA-256
// hashes recorded in snark-artifacts.lock.json. A drift here means either:
//   • the CDN rotated artifacts (a *real* upstream issue), or
//   • our local copies got corrupted / partially downloaded.
//
// Either way, proofs generated by the client wouldn't verify against what
// other clients see, so we want CI to fail loudly.
import { describe, it, expect } from 'vitest';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const LOCK_PATH = join(process.cwd(), 'snark-artifacts.lock.json');
const ARTIFACT_DIR = join(process.cwd(), 'static', 'snark-artifacts', 'semaphore');

type ArtifactRecord = { url: string; bytes: number; sha256: string };
type LockFile = {
	cdnBase: string;
	fetchedAt: string;
	artifacts: Record<string, { wasm: ArtifactRecord; zkey: ArtifactRecord }>;
};

async function loadLock(): Promise<LockFile> {
	const raw = await readFile(LOCK_PATH, 'utf8');
	return JSON.parse(raw);
}

function sha256(buf: Uint8Array): string {
	return createHash('sha256').update(buf).digest('hex');
}

describe('snark artifacts lockfile', () => {
	it('lockfile exists and references the CDN', async () => {
		const lock = await loadLock();
		expect(lock.cdnBase).toMatch(/snark-artifacts\.pse\.dev/);
		expect(Object.keys(lock.artifacts).length).toBeGreaterThan(0);
	});

	it('every depth referenced in the lock has both wasm + zkey present on disk', async () => {
		const lock = await loadLock();
		const missing: string[] = [];
		for (const depth of Object.keys(lock.artifacts)) {
			const wasm = join(ARTIFACT_DIR, depth, `semaphore-${depth}.wasm`);
			const zkey = join(ARTIFACT_DIR, depth, `semaphore-${depth}.zkey`);
			if (!existsSync(wasm)) missing.push(wasm);
			if (!existsSync(zkey)) missing.push(zkey);
		}
		expect(
			missing,
			missing.length > 0
				? `Missing artifacts: ${missing.join(', ')}.\nRun \`npm run snark:fetch\`.`
				: 'all artifacts present'
		).toEqual([]);
	});

	it('every on-disk artifact matches the SHA-256 in the lock', async () => {
		const lock = await loadLock();
		for (const [depth, row] of Object.entries(lock.artifacts)) {
			for (const kind of ['wasm', 'zkey'] as const) {
				const path = join(ARTIFACT_DIR, depth, `semaphore-${depth}.${kind}`);
				if (!existsSync(path)) continue;
				const buf = await readFile(path);
				expect(buf.byteLength, `${kind} depth ${depth} byte length`).toBe(row[kind].bytes);
				expect(sha256(buf), `${kind} depth ${depth} sha256`).toBe(row[kind].sha256);
			}
		}
	});

	it('lockfile records reasonable artifact sizes (sanity: > 100 KiB each, < 100 MiB)', async () => {
		const lock = await loadLock();
		for (const [depth, row] of Object.entries(lock.artifacts)) {
			for (const kind of ['wasm', 'zkey'] as const) {
				expect(row[kind].bytes, `${kind} depth ${depth}`).toBeGreaterThan(100 * 1024);
				expect(row[kind].bytes, `${kind} depth ${depth}`).toBeLessThan(100 * 1024 * 1024);
			}
		}
	});
});
